// src/app/curtain-panel/template-manager/template-manager.component.ts
import { Component, EventEmitter, OnDestroy, Output } from "@angular/core";
import { GenService, Template } from "src/app/gen.service";
import { TemplateEditData } from "../template-editor/template-editor.component";
import { NgxFloatUiPlacements } from "ngx-float-ui";
import { Subscription } from "rxjs";

@Component({
    selector: 'template-manager',
    templateUrl: 'template-manager.component.html',
    styleUrls: ['template-manager.component.scss']
})
export class TemplateManagerComponent implements OnDestroy {
    readonly NgxFloatUiPlacements = NgxFloatUiPlacements;
    readonly templateInfo: string = `Шаблоны позволяют не тратить время на ручной набор названий столбцов, которые вы хотите добавить в информацию о человеке.<br>
    Например, можно создать шаблон ФИО, который при добавлении создаст столбцы "Фамилия", "Имя" и "Отчество" - вводить вручную их больше не придется.`;
    templates: Template[] = [];
    subscription: Subscription;
    @Output() edited: EventEmitter<TemplateEditData> = new EventEmitter();
    @Output() closed: EventEmitter<void> = new EventEmitter();
    constructor(private genService: GenService) {
        this.subscription = this.genService.genData.subscribe((genData) => { this.templates = [...genData.templates]; });
    }

    ngOnDestroy(): void {
        this.subscription.unsubscribe();
    }

    newTemplate() {
        this.edited.emit({ template: { name: "", properties: [] }, oldName: undefined });
    }

    edit(name: string) {
        let editData: TemplateEditData = {
            template: {
                name,
                properties: []
            },
            oldName: name
        };
        const properties = Template.findProperties(name, this.templates);
        if (properties) {
            editData.template.properties = [...properties];
        }
        this.edited.emit(editData);
    }

    delete(name: string) {
        this.genService.deleteTemplate(name);
    }

    close() {
        this.closed.emit();
    }
}
<div id="control">
    <button class="btn btn-primary" (click)="newTemplate()">Новый шаблон</button>
    <div>
        <i-bs name="info-circle" width="1.5rem" height="1.5rem"
            [floatUi]="templateInfo" 
            [placement]="NgxFloatUiPlacements.LEFTSTART"
            [hideOnScroll]="!0"></i-bs>
    </div>
</div>
<div class="accordion" id="templates-accordion">
    <div *ngFor="let templ of templates; let i = index" class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                attr.data-bs-target="#template-collapse{{i}}" aria-expanded="false"
                attr.aria-controls="template-collapse{{i}}">{{templ.name}}</button>
        </h2>
        <div attr.id="template-collapse{{i}}" class="accordion-collapse collapse" data-bs-parent="#templates-accordion">
            <div class="accordion-body">
                <table class="table table-borderless">
                    <tbody>
                        <tr *ngFor="let property of templ.properties">
                            <td>{{property}}</td>
                        </tr>
                    </tbody>
                </table>
                <div class="row">
                    <button class="col btn btn-danger mx-3" (click)="delete(templ.name)">Удалить</button>
                    <button class="col btn btn-success mx-3" (click)="edit(templ.name)">Изменить</button>
                </div>
            </div>
        </div>
    </div>
</div>

// src/lib/components/curtainPanel/TemplateManager.svelte
<script lang="ts">
    import { Template, genData } from "../../store/gen";
    import { createEventDispatcher, onDestroy } from "svelte";
    import { createFloatingActions } from "svelte-floating-ui";
    import { offset, shift, flip } from "svelte-floating-ui/dom";
    import InfoCircle from "../svg/InfoCircle.svelte";
    import type { TemplateEditData } from "./TemplateEditor.svelte";
    import Floating, {
        floatingStructDefault,
        type FloatingStruct,
    } from "../Floating.svelte";

    const dispatch = createEventDispatcher<{
        edit?: TemplateEditData;
        close?: void;
    }>();

    let templates: Template[] = [];
    const unsubscribe = genData.subscribe((v) => {
        templates = [...v.templates];
    });
    onDestroy(unsubscribe);

    let templateInfo: FloatingStruct = floatingStructDefault();
    [templateInfo.ref, templateInfo.content] = createFloatingActions({
        placement: "left-start",
        strategy: "fixed",
        middleware: [offset(10), shift(), flip()],
    });

    function newTemplate() {
        dispatch("edit", {
            template: { name: "", properties: [] },
            oldName: undefined,
        });
    }

    function edit(name: string) {
        let editData: TemplateEditData = {
            template: {
                name,
                properties: [],
            },
            oldName: name,
        };
        const properties = Template.findProperties(name, templates);
        if (properties) {
            editData.template.properties = [...properties];
        }
        dispatch("edit", editData);
    }

    function deleteTemplate(name: string) {
        genData.deleteTemplate(name);
    }
</script>

<div class="host">
    <div id="control">
        <button class="btn btn-primary" on:click={newTemplate}
            >Новый шаблон</button
        >
        <div
            class="d-inline"
            use:templateInfo.ref
            on:mouseenter={() => (templateInfo.show = true)}
            on:mouseleave={() => (templateInfo.show = false)}
        >
            <InfoCircle sideSize={1.5} />
        </div>
    </div>
    <div class="accordion" id="templates-accordion">
        {#each templates as template, i}
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button
                        class="accordion-button collapsed"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#template-collapse{i}"
                        aria-expanded="false"
                        aria-controls="template-collapse{i}"
                        >{template.name}</button
                    >
                </h2>
                <div
                    id="template-collapse{i}"
                    class="accordion-collapse collapse"
                    data-bs-parent="#templates-accordion"
                >
                    <div class="accordion-body">
                        <table class="table table-borderless">
                            <tbody>
                                {#each template.properties as property}
                                    <tr><td>{property}</td></tr>
                                {/each}
                            </tbody>
                        </table>
                        <div class="row">
                            <button
                                class="col btn btn-danger mx-3"
                                on:click={() => deleteTemplate(template.name)}
                                >Удалить</button
                            >
                            <button
                                class="col btn btn-success mx-3"
                                on:click={() => edit(template.name)}
                                >Изменить</button
                            >
                        </div>
                    </div>
                </div>
            </div>
        {/each}
    </div>
</div>

{#if templateInfo.show}
    <Floating contentAction={templateInfo.content}>
        Шаблоны позволяют не тратить время на ручной набор названий столбцов,
        которые вы хотите добавить в информацию о человеке.<br />
        Например, можно создать шаблон ФИО, который при добавлении создаст столбцы
        "Фамилия", "Имя" и "Отчество" - вводить вручную их больше не придется.
    </Floating>
{/if}

<style lang="scss">
    @import "../../../util.scss";

    .host {
        max-height: 100%;
        display: block;
        overflow-y: scroll;
        padding: 15px;
        @include hide-scroll();

        #control {
            display: flex;
            margin-bottom: 15px;

            :last-child {
                display: inline-block;
                margin-left: auto;
            }
        }
    }
</style>
